model_list:
  - model_name: Kimi-K2-Thinking
    litellm_params:
      model: azure_ai/Kimi-K2-Thinking
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY

litellm_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  drop_params: True
